---
name: "veso-plugin-tmdbboxsets"
guid: "bc4aad2e-d3d0-4725-a5e2-fd07949e5b42"
version: "5" # Please increment with each pull request
veso_version: "10.5.0" # The earliest binary-compatible version
owner: "veso"
nicename: "TMDb Box Sets"
description: "Automatically create movie box sets based on TMDb collections"
overview: "Automatically create movie box sets based on TMDb collections"
category: "Metadata"
artifacts:
  - "Veso.Plugin.TMDbBoxSets.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.1"
